# Dockerfile.prod

FROM node:20 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npx prisma generate
RUN npm run build

# ----------

FROM node:20 AS runner
WORKDIR /app

COPY --from=builder /app ./


ENV NODE_ENV=production

EXPOSE 3000
CMD ["npm", "run", "start"]
